### Import

In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.svm import SVC
from sklearn.tree import ExtraTreeClassifier, DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from sklearn.neighbors import KNeighborsClassifier

pd.set_option('display.max_columns', None)

### Load data

In [106]:
df = pd.read_csv('data/clean_df.csv')

In [107]:
df.head(5)

name                      industry  office  size  review_counts  \
0         Google                      Internet      35     3        19400.0   
1      Microsoft  Computer Hardware & Software      34     3        30300.0   
2          Apple  Computer Hardware & Software      25     3        21600.0   
3   US Air Force              Federal Agencies      40     3        17100.0   
4  Cisco Systems  Computer Hardware & Software      25     3        22400.0   

   salaries_count  jobs_count  interviews_count  benefits_count  \
0         43800.0      1900.0           13000.0          4700.0   
1         68800.0      5700.0           10000.0         10000.0   
2         63600.0      4200.0            8500.0          7100.0   
3         19400.0      4800.0            1000.0          7600.0   
4         42500.0      1900.0            4300.0          8000.0   

                      website company_type  revenue       head_quarter  \
0     https://www.google.com/       Public        8  Mountain View, CA   
1  https://www.microsoft.com/       Public        8        Redmond, WA   
2      https://www.apple.com/       Public        8      Cupertino, CA   
3         https://www.af.mil/   Government        8     Washington, DC   
4      https://www.cisco.com/      Private        8       San Jose, CA   

   founded  interview_possitive  interview_negative  interview_neutral  \
0   1998.0                 0.61                0.15               0.23   
1   1975.0                 0.65                0.13               0.21   
2   1976.0                 0.65                0.15               0.20   
3   1947.0                 0.70                0.05               0.24   
4   1984.0                 0.69                0.11               0.19   

   interview_difficulty  benefits_score  rating  \
0                   3.3             4.7     4.5   
1                   3.1             4.5     4.4   
2                   3.0             4.5     4.3   
3                   2.2             4.5     4.2   
4                   3.0             4.2     4.2   

   total_insurance_health_wellness_benefits  health_insurance  \
0                                        13                 1   
1                                        12                 1   
2                                        12                 1   
3                                        11                 1   
4                                        13                 1   

   dental_insurance  FSA  vision insurance  HSA  life_insurance  \
0                 1    1                 1    1               1   
1                 1    1                 1    1               1   
2                 1    1                 1    1               1   
3                 1    0                 1    0               1   
4                 1    1                 1    1               1   

   supplemental_life_insurance  disability_insurance  \
0                            1                     1   
1                            1                     1   
2                            1                     1   
3                            1                     1   
4                            1                     1   

   occupational_accident_insurance  health_care_on_site  mental_health_care  \
0                                1                    1                   1   
1                                1                    1                   1   
2                                1                    0                   1   
3                                1                    1                   1   
4                                1                    1                   1   

   retiree_health_and_medical  accidental_death_and_dismemberment_insurance  \
0                           1                                             1   
1                           0                                             1   
2                           1                                             1   
3              

### Set up X and y

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2233 entries, 0 to 2232
Data columns (total 82 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   name                                          2233 non-null   object 
 1   industry                                      2233 non-null   object 
 2   office                                        2233 non-null   int64  
 3   size                                          2233 non-null   int64  
 4   review_counts                                 2233 non-null   float64
 5   salaries_count                                2233 non-null   float64
 6   jobs_count                                    2233 non-null   float64
 7   interviews_count                              2233 non-null   float64
 8   benefits_count                                2233 non-null   float64
 9   website                                       2233 non-null   o

In [109]:
#df = pd.get_dummies(df, columns=['company_type','category'], drop_first = True)

In [130]:
X = df.drop(columns=['company_type','category','company_rank','size','rating','name','industry','website',
                     'head_quarter'])
y = df['company_rank']

features = X.columns

### Train/Test Split

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100)

### Standar Scalar the data

In [112]:
ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train)
X_test_sc = ss.transform(X_test)

In [113]:
y.mean()

1.8978952082400358

In [114]:
X_train.shape

(1674, 73)

## checking model

### SVC

In [115]:
svc = SVC()
cross_val_score(svc,X,y,cv= 5).mean()

0.4831412204933739

### Random forest

In [116]:
rfc = RandomForestClassifier()
cross_val_score(rfc, X,y, cv=5).mean()

0.5220834461933568

### ADA boost

In [117]:
boost = AdaBoostClassifier()
cross_val_score(boost,X,y,cv=5).mean()

0.49836879646070964

### Logistic Regression

In [118]:
logr= LogisticRegression()
cross_val_score(logr,X,y,cv=5).mean()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0.4370602221085262

### Decicion Tree

In [119]:
tree = DecisionTreeClassifier()
cross_val_score(tree, X,y,cv=5).mean()

0.4621251793220373

### Extra tree

In [120]:
x_trees = ExtraTreeClassifier()
cross_val_score(x_trees, X,y,cv= 5).mean()

0.3976525115117224

### K-NN

In [121]:
knn = KNeighborsClassifier()
cross_val_score(knn, X,y,cv= 5).mean()

0.4442240747986076

In [126]:
pipe = Pipeline([('scaler', StandardScaler()),('boost', LogisticRegression())])
pipe.fit(X_train, y_train)
print(f'Training Score: ', pipe.score(X_train,y_train))
print(f'Validation Score: ', pipe.score(X_test, y_test))
predictions = pipe.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

Training Score:  0.5884109916367981
Validation Score:  0.5295169946332737
[[117  59   9]
 [ 67 129  25]
 [ 22  81  50]]
              precision    recall  f1-score   support

           1       0.57      0.63      0.60       185
           2       0.48      0.58      0.53       221
           3       0.60      0.33      0.42       153

    accuracy                           0.53       559
   macro avg       0.55      0.51      0.52       559
weighted avg       0.54      0.53      0.52       559



In [123]:
pipe = Pipeline([('scaler', StandardScaler()),('boost', RandomForestClassifier())])
pipe.fit(X_train, y_train)
print(f'Training Score: ', pipe.score(X_train,y_train))
print(f'Validation Score: ', pipe.score(X_test, y_test))
predictions = pipe.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

Training Score:  1.0
Validation Score:  0.5617173524150268
[[108  70   7]
 [ 45 167   9]
 [ 14 100  39]]
              precision    recall  f1-score   support

           1       0.65      0.58      0.61       185
           2       0.50      0.76      0.60       221
           3       0.71      0.25      0.37       153

    accuracy                           0.56       559
   macro avg       0.62      0.53      0.53       559
weighted avg       0.60      0.56      0.54       559



In [127]:
pipe = Pipeline([('scaler', StandardScaler()),('boost', GradientBoostingClassifier())])
pipe.fit(X_train, y_train)
print(f'Training Score: ', pipe.score(X_train,y_train))
print(f'Validation Score: ', pipe.score(X_test, y_test))
predictions = pipe.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

Training Score:  0.8154121863799283
Validation Score:  0.5277280858676208
[[106  70   9]
 [ 52 138  31]
 [ 15  87  51]]
              precision    recall  f1-score   support

           1       0.61      0.57      0.59       185
           2       0.47      0.62      0.53       221
           3       0.56      0.33      0.42       153

    accuracy                           0.53       559
   macro avg       0.55      0.51      0.52       559
weighted avg       0.54      0.53      0.52       559



In [125]:
pipe = Pipeline([('scaler', StandardScaler()),('boost', ExtraTreesClassifier())])
pipe.fit(X_train, y_train)
print(f'Training Score: ', pipe.score(X_train,y_train))
print(f'Validation Score: ', pipe.score(X_test, y_test))
predictions = pipe.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

Training Score:  1.0
Validation Score:  0.4937388193202147
[[106  71   8]
 [ 69 138  14]
 [ 24  97  32]]
              precision    recall  f1-score   support

           1       0.53      0.57      0.55       185
           2       0.45      0.62      0.52       221
           3       0.59      0.21      0.31       153

    accuracy                           0.49       559
   macro avg       0.53      0.47      0.46       559
weighted avg       0.52      0.49      0.47       559



In [132]:
boost = GradientBoostingClassifier()
boost.fit(X_train,y_train)

values = boost.feature_importances_

feat = pd.DataFrame(features)
feat['values'] = values
df_feat = feat.sort_values(by= 'values', ascending=False).head(20)

In [133]:
df_feat

0    values
12                            benefits_score  0.197499
2                             salaries_count  0.152357
5                             benefits_count  0.059583
1                              review_counts  0.055063
9                         interview_negative  0.054189
8                        interview_possitive  0.052389
11                      interview_difficulty  0.047453
3                                 jobs_count  0.045167
7                                    founded  0.043886
4                           interviews_count  0.043597
10                         interview_neutral  0.040829
0                                     office  0.015986
6                                    revenue  0.015335
56                         employee_discount  0.012135
27       total_financial_retirement_benefits  0.010447
29                                 plan_401K  0.010431
55             total_perk_discounts_benefits  0.009092
57                      free_lunch_or_snacks  0.008900
13  total_insurance_health_wellness_benefits  0.008792
37           total_family_parenting_benefits  0.008023